/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.math.IntMath;

public class HelloOtus {
    public static void main(String... args) {
        int factorial = IntMath.factorial(5);
        System.out.println(factorial);
    }
}
